version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    #    ports:
    #      - '5672:5672'
    networks:
      - my_network
    expose:
      - '5672'
  auth:
    build:
      context: './auth'
      dockerfile: Dockerfile
#    ports:
#      - '4002:4002'
    networks:
      - my_network
    depends_on:
      - rabbitmq
    restart: always
  store:
    build:
      context: './store'
      dockerfile: Dockerfile
    ports:
      - '4001:4001'
    networks:
      - my_network
    depends_on:
      - rabbitmq
      - auth
    restart: always
networks:
  my_network: