version: '3.8'  

networks:
  app-network:

services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "${AUTH_PORT}:8001"
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  activity:
    build:
      context: ./activities
      dockerfile: Dockerfile
    ports:
      - "${ACTIVITY_PORT}:8003"
    env_file:
      - ./.env
    depends_on:
      - db
      - auth
    networks:
      - app-network
    restart: always

  location:
    build:
      context: ./locations
      dockerfile: Dockerfile
    ports:
      - "${LOCATION_PORT}:8006"
    env_file:
      - ./.env
    depends_on:
      - db
      - auth
      - activity
    networks:
      - app-network
    restart: always

  offer:
    build:
      context: ./offers
      dockerfile: Dockerfile
    ports:
      - "${OFFER_PORT}:8009"
    env_file:
      - ./.env
    depends_on:
      - db
      - auth
      - location
    networks:
      - app-network
    restart: always

  trip:
    build:
      context: ./trips
      dockerfile: Dockerfile
    ports:
      - "${TRIP_PORT}:8002"
    env_file:
      - ./.env
    depends_on:
      - db
      - auth
    networks:
      - app-network
    restart: always

  review:
    build:
      context: ./reviews
      dockerfile: Dockerfile
    ports:
      - "${REVIEW_PORT}:8005"
    env_file:
      - ./.env
    depends_on:
      - db
      - location
    networks:
      - app-network
    restart: always

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "${GATEWAY_PORT}:8000"
    depends_on:
      - trip
      - location
      - auth
      - offer
      - activity
      - review
    networks:
      - app-network
    restart: always

  db:
    image: postgres:latest
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data: